function HideFiles()
  -- hide all files that start with a ../ or a ./
  vim.cmd [[let g:netrw_list_hide=',^\.\.\=/\=$']]
  -- hides all files generated by templ
  vim.cmd [[let g:netrw_list_hide.=',.*_templ.go']]
end

HideFiles()
